subdirs = ''

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    bld(features = 'cxx cxxstlib',
        source = 'octrf/io.cpp octrf/objfuncs.cpp',
        target = 'octrf',
        includes = '.')
